eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8585
spring:
  application:
    name: NEWSLETTER-ADMIN
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:tcp://localhost:8123/mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always